api_login:
    path: '/api/login'

api_refresh:
    path: '/api/refresh'
    controller: gesdinet.jwtrefreshtoken::refresh
        
controllers:
    prefix: '/api'
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
